---
# lego_acme-client/tasks/create_config_file.yml

- name: 'Create the config file in /etc/lego'
  template:
    src: 'etc_lego_config.j2'
    dest: '/etc/lego/config'
    owner: 'root'
    group: 'root'
    mode: '0600'
