---
# lego_acme-client/tasks/create_config_file.yml

- name: 'Create the config file /etc/lego/config'
  ansible.builtin.template:
    src: 'etc_lego_config.j2'
    dest: '/etc/lego/config'
    owner: 'root'
    group: 'root'
    mode: '0600'

- name: 'make sure the directory from lego_path exists'
  ansible.builtin.file:
    path: "{{ lego_path }}"
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0700'
