---
# lego_acme-client/tasks/create_helper_script.yml

- name: 'Create the helper script for certificate renewal'
  ansible.builtin.template:
    src: 'lego_certificate_renew.sh.j2'
    dest: "{{ path_to_install_to }}/lego_certificate_renew.sh"
    owner: 'root'
    group: 'root'
    mode: '0755'
