---
# lego_acme-client/tasks/main.yml

- name: 'Define path to lego binary'
  ansible.builtin.set_fact:
    path_to_lego: "{{ path_to_install_to }}/lego"
  when:
    - 'path_to_lego is undefined'

- name: 'Download binary'
  ansible.builtin.include_tasks: download_binary.yml
  tags:
    - 'installation'
  when:
    - 'download_binary | bool'

- name: 'Create helper script'
  ansible.builtin.include_tasks: create_helper_script.yml
  tags:
    - 'helper_script'

- name: 'Create config file'
  ansible.builtin.include_tasks: create_config_file.yml
  tags:
    - 'config_file'
  when:
    - 'create_lego_config_file | bool'

- name: 'Create systemd timer for certificate renewal'
  ansible.builtin.include_tasks: systemd_timer.yml
  tags:
    - 'systemd_timer'

- name: 'Enable and start the systemd timer for certificate renewal'
  ansible.builtin.service:
    name: 'lego_certificate_renew.timer'
    state: 'started'
    enabled: 'true'
  tags:
    - 'systemd_timer'
  when:
    - 'enable_lego_renew_timer | bool'
