---
# lego_acme-client/tasks/main.yml

- name: 'Download binary on Debian'
  include: download_binary_on_Debian.yml
  tags:
    - 'installation'
  when:
    - 'ansible_distribution == "Debian"'

- name: 'Create helper script'
  include: create_helper_script.yml
  tags:
    - 'helper_script'

- name: 'Create config file'
  include: create_config_file.yml
  tags:
    - 'config_file'
  when:
    - 'lego_config is defined'

- name: 'Create systemd timer for certificate renewal'
  include: systemd_timer.yml
  tags:
    - 'systemd_timer'

- name: 'Enable the systemd timer for certificate renewal'
  service:
    name: 'lego_certificate_renew.timer'
    enabled: 'true'
  when:
    - 'enable_lego_renew_timer | bool'
